# Generated by Django 5.2 on 2025-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
